// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3mVmNaDLIk-psjYrkQw-oyygzwTBiGA0',
    appId: '1:658177107812:android:3e1abda782e4bcaaea3c71',
    messagingSenderId: '658177107812',
    projectId: 'booklife-16da2',
    storageBucket: 'booklife-16da2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMqLDBqePyrM0rVGBX3jLel4MK-xYiqdM',
    appId: '1:658177107812:ios:ceb9ebd5de3df5b8ea3c71',
    messagingSenderId: '658177107812',
    projectId: 'booklife-16da2',
    storageBucket: 'booklife-16da2.firebasestorage.app',
    iosBundleId: 'com.example.bookLife',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDDuC5ivaJOIklQSft0aS5b25SRSCkCw8',
    appId: '1:658177107812:web:a5984572b0f129ffea3c71',
    messagingSenderId: '658177107812',
    projectId: 'booklife-16da2',
    authDomain: 'booklife-16da2.firebaseapp.com',
    storageBucket: 'booklife-16da2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMqLDBqePyrM0rVGBX3jLel4MK-xYiqdM',
    appId: '1:658177107812:ios:ceb9ebd5de3df5b8ea3c71',
    messagingSenderId: '658177107812',
    projectId: 'booklife-16da2',
    storageBucket: 'booklife-16da2.firebasestorage.app',
    iosBundleId: 'com.example.bookLife',
  );

}